default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: 'username'
  password: 'password'
  host: <%= ENV['IP'] %>

development:
  <<: *default
  database: project_development

test:
  <<: *default
  database: project_test